#开发环境数据库文件
server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/person_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zhangchuang2726

    #开启日志Mybatis-plus日志
  data:
    redis:
      host: 192.168.1.110
      port: 6379
      password: zhangchuang2726
      database: 8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zhangchuang.**.entity
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值

# 阿里云OSS配置
aliyun:
  oss:
    file-domain: https://bed.oss.zhangchuangla.cn/
    end-point: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSFwfMsPQwsr8Q3pbUA
    access-key-secret: DMu2VMrBrKZADqrDLXZgdXVJLUQiOM
    bucket-name: chuang-drawingbed

#Minio 文件上传
minio:
  fileDomain: http://bed.data-center.zhangchuangla.cn/
  endpoint: http://192.168.1.120:9000/
  accessKey: cwytEbLXyBo2Tul2C9OZ
  secretKey: UGGQUnHCjjooNlrZZfO1WCNEB1OvCriYOWX47Oi5
  bucketName: bed
app:
  config:
    upload-path: /Users/zhangchuang/DevelopFileUpload
    ip-address-enable: true
    strictLoginEnable: true
token:
  expire: 300000
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
user:
  password:
    lock-time: 3
    max-retry-count: 5
