app:
  config:
    upload-path: D:\\DevelopUploads\\personApp # This seems to be an old config, will be superseded by new storage config if local is active
    enable-trash: true # This too might be superseded
  name: Chuang
  version: 1.0.0
#开发环境数据库文件
server:
  port: 8080
spring:
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    redis:
      host: 192.168.10.110
      port: 6379
      database: 0
      password: zhangchuang2726
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    syntax-highlight:
      activated: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  cache:
    disabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.zhangchuangla.**.entity
  mapper-locations:
    - classpath*:mapper/**/**.xml
    - classpath*:cn/zhangchuangla/**/mapper/xml/**.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值


security:
  expire: 300000
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
  password-config:
    lock-time: 3
    max-retry-count: 5
  session:
    access-token-expire-time: 7200000
    refresh-token-expire-time: 2592000
    single-login: false

# ===================================================================
# 新的存储配置
# ===================================================================
storage:
  # --- 本地存储配置 ---
  local:
    # 本地存储的根路径（推荐使用绝对路径）
    # 示例：/var/www/uploads 或 D:/uploads
    # 确保此路径存在，并且应用程序具有写入权限。
    root-path-or-bucket-name: "/Users/zhangchuang/projects/app-backend/uploads" # <<< 请更新此路径
    # 文件的公开访问基础URL（如果由Web服务器或Spring资源处理程序直接提供）
    # 示例：https://yourdomain.com/uploads 或者如果是通过Spring提供，可以是 /resources/uploads
    file-domain: "/static-uploads" # 如果你为root-path设置了名为/static-uploads的资源处理器，请参考此示例
    enable-trash: true
    trash-directory-name: "trash"

  # --- MinIO 配置 ---
  minio:
    endpoint: "http://your-minio-server:9000"
    access-key: "YOUR_MINIO_ACCESS_KEY"
    secret-key: "YOUR_MINIO_SECRET_KEY"
    root-path-or-bucket-name: "your-minio-bucket-name" # 这里填写的是存储桶名称
    file-domain: "" # 示例："https://minio.yourdomain.com/your-bucket-name"
    enable-trash: true
    trash-directory-name: "trash"

  # --- 阿里云OSS 配置 ---
  aliyun-oss:
    endpoint: "oss-cn-beijing.aliyuncs.com"
    access-key-id: "YOUR_ALIYUN_ACCESS_KEY_ID"
    access-key-secret: "YOUR_ALIYUN_ACCESS_KEY_SECRET"
    root-path-or-bucket-name: "your-aliyun-oss-bucket-name"
    file-domain: "" # 示例："https://your-oss-domain.com"
    enable-trash: true
    trash-directory-name: "trash"

  # --- 腾讯COS 配置 ---
  tencent-cos:
    region: "ap-beijing"
    secret-id: "YOUR_TENCENT_COS_SECRET_ID"
    secret-key: "YOUR_TENCENT_COS_SECRET_KEY"
    root-path-or-bucket-name: "your-tencent-cos-bucket-name-appid"
    file-domain: "" # 示例："https://your-cos-domain.com"
    enable-trash: true
    trash-directory-name: "trash"
