app:
  config:
    upload-path: /Users/zhangchuang/DevelopFileUpload
    enable-trash: true
  name: Chuang
  version: 0.1
#开发环境数据库文件
server:
  port: 8080
spring:
  profiles:
    active: druid,rabbitmq,quartz #激活配置文件
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      host: 192.168.10.110
      port: 6379
      database: 0
      password: zhangchuang2726
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    syntax-highlight:
      activated: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  cache:
    disabled: true

# 存储系统配置
storage:
  # 当数据库中未找到主存储配置时，将使用此默认配置。设置为 "local" 表示优先使用本地存储；
  # 若设置为 "minio"，则表示在数据库配置不可用时降级使用 MinIO 配置；若未指定 MinIO 配置，则仍将默认使用本地存储。
  active-type: local
  # 本地存储配置
  local:
    uploadPath: ${app.config.upload-path}
    file-domain: http://localhost:8080/
    enable-trash: ${app.config.enable-trash}

  # MinIO 配置
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: echopro
    file-domain: http://localhost:9000/echopro
    real-delete: false

  # 阿里云 OSS 配置
  aliyun-oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucket-name: echopro-oss
    file-domain: https://echopro-oss.oss-cn-hangzhou.aliyuncs.com
    real-delete: false

  # 腾讯云 COS 配置
  tencent-cos:
    region: ap-guangzhou
    secret-id: ${TENCENT_SECRET_ID:}
    secret-key: ${TENCENT_SECRET_KEY:}
    bucket-name: echopro-1234567890
    file-domain: https://echopro-1234567890.cos.ap-guangzhou.myqcloud.com
    real-delete: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.zhangchuangla.**.entity
  mapper-locations:
    - classpath*:mapper/**/**.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值


security:
  expire: 300000
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
  password-config:
    lock-time: 3
    max-retry-count: 5
  session:
    access-token-expire-time: 7200000
    refresh-token-expire-time: 2592000
    single-login: false
