app:
  config:
    name: 后台管理系统
    author: zhangchuang
    version: alpha 0.1
    description: 基本后台管理系统，采用SpringBoot3+SpringSecurity+MybatisPlus
    copyright: Copyright © 2024-2025 zhangchuang All Rights Reserved.
    ip-address-enable: false
    strictLoginEnable: false
    upload-path: D:\DevelopUploads\personApp
    enable-trash: true
#开发环境数据库文件
server:
  port: 8080
spring:
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      host: 192.168.10.110
      port: 6379
      database: 0
      password: zhangchuang2726
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.zhangchuangla.**.entity
  mapper-locations:
    - classpath*:mapper/**/**.xml
    - classpath*:cn/zhangchuangla/**/mapper/xml/**.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值


security:
  expire: 300000
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
  password-config:
    lock-time: 3
    max-retry-count: 5
  session:
    access-token-expire-time: 7200
    refresh-token-expire-time: 2592000
    single-login: true
