app:
  config:
    name: 后台管理系统
    author: zhangchuang
    version: alpha 0.1
    description: 基本后台管理系统，采用SpringBoot3+SpringSecurity+MybatisPlus+Redis+MySQL+Minio等技术栈开发
    copyright: Copyright © 2024-2025 zhangchuang All Rights Reserved.
    ip-address-enable: false
    strictLoginEnable: false
    upload-path: D:\DevelopUploads\personApp
#开发环境数据库文件
server:
  port: 8080
spring:
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: zhangchuang2726

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.zhangchuangla.**.entity
  mapper-locations:
    - classpath*:mapper/**/**.xml
    - classpath*:cn/zhangchuangla/**/mapper/xml/**.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值

# 阿里云OSS配置
aliyun:
  oss:
    file-domain: https://bed.oss.zhangchuangla.cn/
    end-point: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSFwfMsPQwsr8Q3pbUA
    access-key-secret: DMu2VMrBrKZADqrDLXZgdXVJLUQiOM
    bucket-name: chuang-drawingbed

#Minio 文件上传
minio:
  fileDomain: https://bed.data-center.zhangchuangla.cn/
  endpoint: http://192.168.1.120:9000/
  accessKey: cwytEbLXyBo2Tul2C9OZ
  secretKey: UGGQUnHCjjooNlrZZfO1WCNEB1OvCriYOWX47Oi5
  bucketName: bed
token:
  expire: 300000
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
user:
  password:
    lock-time: 3
    max-retry-count: 5
  login:
    #最大登录会话数,0代表不限制,过大的会话数会影响登录性能
    max-login-session: 0
