app:
  config:
    # 如果设置本地存储访问,这边上传的访问路径要和存储配置那边的路径一致,否则上传的文件无法访问
    upload-path: /Users/zhangchuang/DevelopFileUpload
  name: EchoPro
  version: 0.9.0
#开发环境数据库文件
server:
  port: 8080
spring:
  profiles:
    active: druid,rabbitmq,quartz,monitor,storage #激活配置文件
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: 192.168.10.110
      port: 6379
      database: 0
      password: zhangchuang2726
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    syntax-highlight:
      activated: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.zhangchuangla.**.entity
  mapper-locations:
    - classpath*:mapper/**/**.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值

security:
  secret: zhangchuang2726zhangchuang2726zhangchuang2726
  header: Authorization
  password-config:
    lock-time: 3
    max-retry-count: -1
  session:
    access-token-expire-time: 7200000
    refresh-token-expire-time: 2592000
    max-sessions-per-client:
      pc: -1
      mini-program: -1
      web: -1
      unknown: -1
      mobile: -1
    multi-device: true
    token-prefix: null
